# 如何计算时间滑动窗口统计变量

In [ ]:
import pandas as pd
import numpy as np
import datetime
import time
import timeit

In [95]:
df = pd.DataFrame(np.random.randn(10000,10),index = xrange(10000),columns = list('abcdefghij'))

In [96]:
df

a         b         c         d         e         f         g  \
0     0.334908  1.772868 -0.923213  1.052904  1.524496 -0.139358 -1.526997   
1     0.766120  0.258490 -0.187979  1.528881  1.671347 -1.764962 -2.531285   
2     0.109673  1.061700 -0.545651 -0.516764  1.483462  0.686994  1.428703   
3    -1.036246  1.457020  0.667350 -1.875718  1.403239 -0.584255 -1.905242   
4    -0.285157  0.243611  0.132073 -0.003974  1.093359 -1.419841  0.854478   
5     1.406196 -0.057472  0.231067  0.441137  0.744521 -0.007519  2.112322   
6    -0.441358  1.646965  1.359210 -1.072371  0.227582 -0.381263  0.672033   
7    -1.045184  1.013175  1.492118 -0.155969  1.690675 -1.698750  0.767843   
8     0.216430 -0.154969 -0.383590  0.096926 -0.252922  0.297951 -0.098447   
9    -0.166080 -0.819054 -0.393750  3.400256 -1.503749  0.010735  1.166898   
10    0.543930  0.454962 -0.330448 -0.178206 -0.490383  0.452927  0.211551   
11    0.307537 -0.477961  0.031726  0.481823  0.229850 -0.337094 -1.062544   
12    1.493918 -0.550147 -0.068125 -0.730431 -1.406599  0.704774 -0.844603   
13    0.914603 -1.325066  0.474061  1.293614 -1.361290 -0.118651 -0.015092   
14    0.417913 -1.027343  0.247587 -0.038155  0.419915 -0.003117 -0.396209   
15    0.591053 -1.388722 -0.625968  1.481401  0.172228 -0.142935 -1.185804   
16    0.286604  0.140418  0.306229  0.968889 -0.420772  0.615141  1.078998   
17    0.309958 -0.088176 -1.202340  1.335548  1.997802 -1.079868 -0.557500   
18   -0.193594  0.421294  0.687016  0.363221 -0.904192 -0.111123 -0.471630   
19   -1.869388  1.753319 -2.996725  1.144480  0.201206 -0.387704  0.786093   
20   -1.121838  1.140608 -0.031644 -0.031027  0.621770  1.933589 -0.609883   
21   -1.065166  0.534428  0.034811 -0.344327  1.481811 -1.784486  1.896019   
22   -0.538203 -0.865046 -0.218789 -1.361878 -0.370630 -0.058940 -0.570785   
23    0.763712 -0.756745 -1.709057  1.491378  0.619457  0.214315  0.359163   
24    0.270008  1.868867 -0.814030  1.243677  1.265086 -1.374939  1.376747   
25    1.173515 -0.499961 -0.268676 -0.698917 -1.105483 -0.632711  0.426568   
26    0.694873  0.289022 -0.390891  1.430320  1.472394 -1.553852 -0.464725   
27    0.593362  0.192021 -0.051022  0.179186 -2.325352  0.535453 -0.411701   
28   -1.201179 -1.694361  0.442636  0.440087 -1.946855 -0.747248  0.427787   
29   -0.254020  0.825949  0.740516  0.318944  0.469920 -1.580521 -0.831842   
...        ...       ...       ...       ...       ...       ...       ...   
9970 -1.239857  0.969756  2.255597 -0.598430  0.284462  0.350063  1.244268   
9971  0.991815 -0.592272 -0.404405  0.182824 -0.091651 -0.633327 -1.778807   
9972  1.372708 -0.095499  1.203439  0.596263 -1.962796  2.186668  0.655215   
9973  0.574818 -0.697787 -1.053432 -1.204973  2.325863 -0.309920  0.507868   
9974  0.679233 -0.338582 -0.626218  0.318364  0.198161  1.769026  0.510294   
9975 -1.633185 -0.081019  0.145032 -0.835063 -1.965250 -2.497836  1.726248   
9976 -0.200785  0.084750  0.203772 -1.672477  0.283055  1.914116  0.543973   
9977 -0.293152 -0.820772  1.284260  1.374118 -0.328916  0.840450 -0.061131   
9978 -0.790584 -1.352202 -0.876033 -1.439964 -1.681197 -2.098152 -0.065651   
9979  0.354785  0.133252 -1.032974  1.128729 -1.244525 -0.855955 -0.601835   
9980  0.531351  0.320238 -0.607582 -1.167800  1.371279 -0.437650  0.666751   
9981 -0.459705  0.448279  0.613518 -0.908043  1.167331 -0.010139  2.204739   
9982 -2.008348 -0.773646 -0.150560 -0.455071 -0.997758  0.153924 -0.117979   
9983  0.357242  0.030753  0.276420 -0.207087 -0.241183 -1.355321 -0.567175   
9984 -0.484547  1.177951 -0.249074  1.429156  0.715206  0.646828  1.695335   
9985 -0.026202  0.995867  0.192794  0.151547 -0.242182  0.747131  0.424019   
9986 -0.510573 -1.234348 -0.800609  0.437844  0.946977 -0.632422  0.524797   
9987 -0.555029  0.403665  0.537565 -1.133843 -0.215341  0.666198 -0.496901   
9988 -1.560467 -1.187868 -0.401017 -0.080939  0.336027 -1.182143  0.318871   
9989  0.519066  0.838236 -0.088372 

In [97]:
x = datetime.date.today()

In [98]:
x

datetime.date(2016, 7, 11)

In [99]:
rng = pd.date_range(x,periods = df.shape[0],freq='D')

In [100]:
rng

DatetimeIndex(['2016-07-11', '2016-07-12', '2016-07-13', '2016-07-14',
               '2016-07-15', '2016-07-16', '2016-07-17', '2016-07-18',
               '2016-07-19', '2016-07-20',
               ...
               '2043-11-17', '2043-11-18', '2043-11-19', '2043-11-20',
               '2043-11-21', '2043-11-22', '2043-11-23', '2043-11-24',
               '2043-11-25', '2043-11-26'],
              dtype='datetime64[ns]', length=10000, freq='D')

In [101]:
df = df.set_index(rng)

In [102]:
df

a         b         c         d         e         f  \
2016-07-11  0.334908  1.772868 -0.923213  1.052904  1.524496 -0.139358   
2016-07-12  0.766120  0.258490 -0.187979  1.528881  1.671347 -1.764962   
2016-07-13  0.109673  1.061700 -0.545651 -0.516764  1.483462  0.686994   
2016-07-14 -1.036246  1.457020  0.667350 -1.875718  1.403239 -0.584255   
2016-07-15 -0.285157  0.243611  0.132073 -0.003974  1.093359 -1.419841   
2016-07-16  1.406196 -0.057472  0.231067  0.441137  0.744521 -0.007519   
2016-07-17 -0.441358  1.646965  1.359210 -1.072371  0.227582 -0.381263   
2016-07-18 -1.045184  1.013175  1.492118 -0.155969  1.690675 -1.698750   
2016-07-19  0.216430 -0.154969 -0.383590  0.096926 -0.252922  0.297951   
2016-07-20 -0.166080 -0.819054 -0.393750  3.400256 -1.503749  0.010735   
2016-07-21  0.543930  0.454962 -0.330448 -0.178206 -0.490383  0.452927   
2016-07-22  0.307537 -0.477961  0.031726  0.481823  0.229850 -0.337094   
2016-07-23  1.493918 -0.550147 -0.068125 -0.730431 -1.406599  0.704774   
2016-07-24  0.914603 -1.325066  0.474061  1.293614 -1.361290 -0.118651   
2016-07-25  0.417913 -1.027343  0.247587 -0.038155  0.419915 -0.003117   
2016-07-26  0.591053 -1.388722 -0.625968  1.481401  0.172228 -0.142935   
2016-07-27  0.286604  0.140418  0.306229  0.968889 -0.420772  0.615141   
2016-07-28  0.309958 -0.088176 -1.202340  1.335548  1.997802 -1.079868   
2016-07-29 -0.193594  0.421294  0.687016  0.363221 -0.904192 -0.111123   
2016-07-30 -1.869388  1.753319 -2.996725  1.144480  0.201206 -0.387704   
2016-07-31 -1.121838  1.140608 -0.031644 -0.031027  0.621770  1.933589   
2016-08-01 -1.065166  0.534428  0.034811 -0.344327  1.481811 -1.784486   
2016-08-02 -0.538203 -0.865046 -0.218789 -1.361878 -0.370630 -0.058940   
2016-08-03  0.763712 -0.756745 -1.709057  1.491378  0.619457  0.214315   
2016-08-04  0.270008  1.868867 -0.814030  1.243677  1.265086 -1.374939   
2016-08-05  1.173515 -0.499961 -0.268676 -0.698917 -1.105483 -0.632711   
2016-08-06  0.694873  0.289022 -0.390891  1.430320  1.472394 -1.553852   
2016-08-07  0.593362  0.192021 -0.051022  0.179186 -2.325352  0.535453   
2016-08-08 -1.201179 -1.694361  0.442636  0.440087 -1.946855 -0.747248   
2016-08-09 -0.254020  0.825949  0.740516  0.318944  0.469920 -1.580521   
...              ...       ...       ...       ...       ...       ...   
2043-10-28 -1.239857  0.969756  2.255597 -0.598430  0.284462  0.350063   
2043-10-29  0.991815 -0.592272 -0.404405  0.182824 -0.091651 -0.633327   
2043-10-30  1.372708 -0.095499  1.203439  0.596263 -1.962796  2.186668   
2043-10-31  0.574818 -0.697787 -1.053432 -1.204973  2.325863 -0.309920   
2043-11-01  0.679233 -0.338582 -0.626218  0.318364  0.198161  1.769026   
2043-11-02 -1.633185 -0.081019  0.145032 -0.835063 -1.965250 -2.497836   
2043-11-03 -0.200785  0.084750  0.203772 -1.672477  0.283055  1.914116   
2043-11-04 -0.293152 -0.820772  1.284260  1.374118 -0.328916  0.840450   
2043-11-05 -0.790584 -1.352202 -0.876033 -1.439964 -1.681197 -2.098152   
2043-11-06  0.354785  0.133252 -1.032974  1.128729 -1.244525 -0.855955   
2043-11-07  0.531351  0.320238 -0.607582 -1.167800  1.371279 -0.437650   
2043-11-08 -0.459705  0.448279  0.613518 -0.908043  1.167331 -0.010139   
2043-11-09 -2.008348 -0.773646 -0.150560 -0.455071 -0.997758  0.153924   
2043-11-10  0.357242  0.030753  0.276420 -0.207087 -0.241183 -1.355321   
2043-11-11 -0.484547  1.177951 -0.249074  1.429156  0.715206  0.646828   
2043-11-12 -0.026202  0.995867  0.192794  0.151547 -0.242182  0.747131   
2043-11-13 -0.510573 -1.234348 -0.800609  0.437844  0.946977 -0.632422   
2043-11-14 -0.555029  0.403665  0.537565 -1.133843 -0.215341  0.666198   
2043-11-15 -1.560467 -1.187868 -0.401017 -0.080939  0.336027 -1.182143   
2043-11-16  0.519066  0.838236 -0.088372 -0.498801 -1.182867  0.777854   
2043-11-17  0.736777  2.323738  1.711328 -0.074407 -0.897283  0.835253   
2043-11-18  0.424638 -1.456766 -0.898737 -0.635387  1.681227 -0.298690   
2043-11-19 -0.680417  0

In [103]:
arr = df.values

In [104]:
arr

array([[ 0.33490815,  1.7728678 , -0.92321311, ...,  0.23345243,
        -0.90498938, -0.36449469],
       [ 0.76612027,  0.25848961, -0.18797914, ...,  0.64272357,
         0.13445674, -0.15535012],
       [ 0.10967294,  1.06170044, -0.54565147, ..., -2.1754273 ,
         0.70461324,  0.07479865],
       ..., 
       [-1.10994491,  0.13485614, -1.55195582, ..., -1.5929953 ,
         1.19570118, -0.20196886],
       [ 2.38324604,  0.39459914, -0.90810632, ...,  0.44286329,
        -0.44380158,  0.60871314],
       [-1.32991394,  0.15954519, -0.86354692, ...,  0.56525075,
        -1.02018577, -0.97845277]])

In [109]:
t1 = time.clock()
%timeit df['avg_10'] = pd.rolling_mean(df.a,10)
t2 = time.clock()

1000 loops, best of 3: 562 µs per loop


In [110]:
df

a         b         c         d         e         f  \
2016-07-11  0.334908  1.772868 -0.923213  1.052904  1.524496 -0.139358   
2016-07-12  0.766120  0.258490 -0.187979  1.528881  1.671347 -1.764962   
2016-07-13  0.109673  1.061700 -0.545651 -0.516764  1.483462  0.686994   
2016-07-14 -1.036246  1.457020  0.667350 -1.875718  1.403239 -0.584255   
2016-07-15 -0.285157  0.243611  0.132073 -0.003974  1.093359 -1.419841   
2016-07-16  1.406196 -0.057472  0.231067  0.441137  0.744521 -0.007519   
2016-07-17 -0.441358  1.646965  1.359210 -1.072371  0.227582 -0.381263   
2016-07-18 -1.045184  1.013175  1.492118 -0.155969  1.690675 -1.698750   
2016-07-19  0.216430 -0.154969 -0.383590  0.096926 -0.252922  0.297951   
2016-07-20 -0.166080 -0.819054 -0.393750  3.400256 -1.503749  0.010735   
2016-07-21  0.543930  0.454962 -0.330448 -0.178206 -0.490383  0.452927   
2016-07-22  0.307537 -0.477961  0.031726  0.481823  0.229850 -0.337094   
2016-07-23  1.493918 -0.550147 -0.068125 -0.730431 -1.406599  0.704774   
2016-07-24  0.914603 -1.325066  0.474061  1.293614 -1.361290 -0.118651   
2016-07-25  0.417913 -1.027343  0.247587 -0.038155  0.419915 -0.003117   
2016-07-26  0.591053 -1.388722 -0.625968  1.481401  0.172228 -0.142935   
2016-07-27  0.286604  0.140418  0.306229  0.968889 -0.420772  0.615141   
2016-07-28  0.309958 -0.088176 -1.202340  1.335548  1.997802 -1.079868   
2016-07-29 -0.193594  0.421294  0.687016  0.363221 -0.904192 -0.111123   
2016-07-30 -1.869388  1.753319 -2.996725  1.144480  0.201206 -0.387704   
2016-07-31 -1.121838  1.140608 -0.031644 -0.031027  0.621770  1.933589   
2016-08-01 -1.065166  0.534428  0.034811 -0.344327  1.481811 -1.784486   
2016-08-02 -0.538203 -0.865046 -0.218789 -1.361878 -0.370630 -0.058940   
2016-08-03  0.763712 -0.756745 -1.709057  1.491378  0.619457  0.214315   
2016-08-04  0.270008  1.868867 -0.814030  1.243677  1.265086 -1.374939   
2016-08-05  1.173515 -0.499961 -0.268676 -0.698917 -1.105483 -0.632711   
2016-08-06  0.694873  0.289022 -0.390891  1.430320  1.472394 -1.553852   
2016-08-07  0.593362  0.192021 -0.051022  0.179186 -2.325352  0.535453   
2016-08-08 -1.201179 -1.694361  0.442636  0.440087 -1.946855 -0.747248   
2016-08-09 -0.254020  0.825949  0.740516  0.318944  0.469920 -1.580521   
...              ...       ...       ...       ...       ...       ...   
2043-10-28 -1.239857  0.969756  2.255597 -0.598430  0.284462  0.350063   
2043-10-29  0.991815 -0.592272 -0.404405  0.182824 -0.091651 -0.633327   
2043-10-30  1.372708 -0.095499  1.203439  0.596263 -1.962796  2.186668   
2043-10-31  0.574818 -0.697787 -1.053432 -1.204973  2.325863 -0.309920   
2043-11-01  0.679233 -0.338582 -0.626218  0.318364  0.198161  1.769026   
2043-11-02 -1.633185 -0.081019  0.145032 -0.835063 -1.965250 -2.497836   
2043-11-03 -0.200785  0.084750  0.203772 -1.672477  0.283055  1.914116   
2043-11-04 -0.293152 -0.820772  1.284260  1.374118 -0.328916  0.840450   
2043-11-05 -0.790584 -1.352202 -0.876033 -1.439964 -1.681197 -2.098152   
2043-11-06  0.354785  0.133252 -1.032974  1.128729 -1.244525 -0.855955   
2043-11-07  0.531351  0.320238 -0.607582 -1.167800  1.371279 -0.437650   
2043-11-08 -0.459705  0.448279  0.613518 -0.908043  1.167331 -0.010139   
2043-11-09 -2.008348 -0.773646 -0.150560 -0.455071 -0.997758  0.153924   
2043-11-10  0.357242  0.030753  0.276420 -0.207087 -0.241183 -1.355321   
2043-11-11 -0.484547  1.177951 -0.249074  1.429156  0.715206  0.646828   
2043-11-12 -0.026202  0.995867  0.192794  0.151547 -0.242182  0.747131   
2043-11-13 -0.510573 -1.234348 -0.800609  0.437844  0.946977 -0.632422   
2043-11-14 -0.555029  0.403665  0.537565 -1.133843 -0.215341  0.666198   
2043-11-15 -1.560467 -1.187868 -0.401017 -0.080939  0.336027 -1.182143   
2043-11-16  0.519066  0.838236 -0.088372 -0.498801 -1.182867  0.777854   
2043-11-17  0.736777  2.323738  1.711328 -0.074407 -0.897283  0.835253   
2043-11-18  0.424638 -1.456766 -0.898737 -0.635387  1.681227 -0.298690   
2043-11-19 -0.680417  0

In [111]:
#numpy methods
#def f(arr,td):
 #   x = np.zeros(arr.shape)
#    for i in xrange(td):
        

In [113]:
t3 = time.clock()
%timeit y = np.convolve(df.values[:,0],np.ones(10,),'valid')/10
t4 = time.clock()

The slowest run took 14.19 times longer than the fastest. This could mean that an intermediate result is being cached 
10000 loops, best of 3: 85.8 µs per loop


In [76]:
arr[:,0]

array([ 0.60329448,  0.03882076,  0.27066905, ...,  0.39340854,
       -1.07165464, -0.36606199])

In [77]:
y

array([-0.01030826, -0.12069752, -0.099219  , ..., -0.2750428 ,
       -0.49234789, -0.54564441])

In [78]:
y.shape

(9991L,)